# Site settings
title: PRCPTION Travel, Inc.
email: info@perceptiontravel.tv
url: https://prcptiontravel.com
description: "Facilitating global cooperative production of uplifting digital media. It's the smiles, not the fear!"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: &copy; PRCPTION Travel, Inc.

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/prcptiontravel
  - title: facebook
    url: https://facebook.com/prcptiontravel
  - title: github
    url: https://github.com/prcptiontravel

# Build settings
markdown: kramdown
permalink: pretty
